

-- Create PUBLISHER table
CREATE TABLE PUBLISHER (
    PID INT PRIMARY KEY,
    PNAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    STATE VARCHAR(50),
    PHONE VARCHAR(15),
    EMAILID VARCHAR(50)
);

-- Create BOOK table
CREATE TABLE BOOK (
    ISBN INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(100),
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(10, 2),
    COPYRIGHT_DATE DATE,
    YEAR INT,
    PAGE_COUNT INT,
    PID INT,
    FOREIGN KEY (PID) REFERENCES PUBLISHER(PID)
);

-- Create AUTHOR table
CREATE TABLE AUTHOR (
    AID INT PRIMARY KEY,
    ANAME VARCHAR(50),
    STATE VARCHAR(50),
    CITY VARCHAR(50),
    ZIP VARCHAR(10),
    PHONE VARCHAR(15),
    URL VARCHAR(100)
);

-- Insert data into PUBLISHER table
INSERT INTO PUBLISHER (PID, PNAME, ADDRESS, STATE, PHONE, EMAILID) VALUES
(1, 'MEHTA', '123 Mehta St', 'Maharashtra', '9876543210', 'contact@mehta.com'),
(2, 'ABC Publishers', '456 ABC Ave', 'Delhi', '8765432109', 'info@abcpublishers.com');

-- Insert data into BOOK table
INSERT INTO BOOK (ISBN, BOOK_TITLE, CATEGORY, PRICE, COPYRIGHT_DATE, YEAR, PAGE_COUNT, PID) VALUES
(101, 'Half Girlfriend', 'Fiction', 300.00, '2015-01-10', 2015, 250, 1),
(102, 'Database Systems', 'Education', 500.00, '2008-06-12', 2008, 350, 2),
(103, 'Learning SQL', 'Education', 400.00, '2005-11-20', 2005, 220, 1);

-- Insert data into AUTHOR table
INSERT INTO AUTHOR (AID, ANAME, STATE, CITY, ZIP, PHONE, URL) VALUES
(1, 'CHETAN BHAGAT', 'Maharashtra', 'Mumbai', '400001', '9123456789', 'http://chetanbhagat.com'),
(2, 'Abraham Silberschatz', 'Maharashtra', 'Pune', '411001', '9123456788', 'http://silberschatz.com'),
(3, 'Korth', 'Delhi', 'New Delhi', '110001', '9123456787', 'http://korth.com');

SELECT CITY, PHONE, URL 
FROM AUTHOR 
WHERE ANAME = 'CHETAN BHAGAT';

SELECT B.BOOK_TITLE, B.PRICE, A.ANAME, A.URL
FROM BOOK B
JOIN PUBLISHER P ON B.PID = P.PID
JOIN AUTHOR A ON A.AID = B.ISBN  -- assuming ISBN matches to author ID for simplicity
WHERE P.PNAME = 'MEHTA';

UPDATE PUBLISHER 
SET PHONE = '123456' 
WHERE PNAME = 'MEHTA';

SELECT P.PNAME, AVG(B.PRICE) AS AvgPrice, MAX(B.PRICE) AS MaxPrice, MIN(B.PRICE) AS MinPrice
FROM BOOK B
JOIN PUBLISHER P ON B.PID = P.PID
GROUP BY P.PNAME;

DELETE FROM BOOK 
WHERE PAGE_COUNT < 100;

SELECT * 
FROM AUTHOR 
WHERE CITY = 'Pune' AND ANAME LIKE 'C%';

SELECT * 
FROM AUTHOR 
WHERE CITY = (SELECT CITY FROM AUTHOR WHERE ANAME = 'Korth');

SELECT * 
FROM BOOK 
WHERE COPYRIGHT_DATE < '2010-01-01';

